### ISSUE TITLE
这东西怎么用呢？

### ISSUE THREAD

**Issue by tyronetown** [zbq/TdxDataServer#1]
怎么配置，有示例吗？

**Comment by zbq** [comment]
只是个玩具示例，不用太当真。
Plugin是符合通达信插件要求的DLL，放在通达信目录，通达信启动插件选股后，会加载这个DLL。这个DLL被加载后会保存查询行情的函数接口，并加载DataServer DLL，DataServer会启动一个网络服务，代理客户端的查询请求。
